### ISSUE TITLE
Unable to download the training data and list for FCN

### ISSUE THREAD

**Issue by wangyida** [24hours/tf_fcn#1]
HI, I can't open the [URL](http://www.cs.berkeley.edu/~bharath2/codes/SBD/download.html) to get necessary data to train the FCN basd on your codes, is this exist?

**Comment by 24hours** [comment]
Hi, Sorry

I did not expect there will be issue raised in this repo. 

https://www2.eecs.berkeley.edu/Research/Projects/CS/vision/grouping/resources.html 

The author have changed the path. You should use the link about to obtain sbdd data.
